services:
  _defaults:
    autowire: true
    autoconfigure: true
  Alnv\ProSearchIndexerContaoAdapterBundle\Cron\DeleteIndices:
    tags:
      - { name: contao.cron, interval: minutely }
  Alnv\ProSearchIndexerContaoAdapterBundle\Controller\ElasticsearchController:
    public: true
  Alnv\ProSearchIndexerContaoAdapterBundle\Controller\ElasticsearchProxyController:
    public: true
  Alnv\ProSearchIndexerContaoAdapterBundle\Controller\StatController:
    public: true
  Alnv\ProSearchIndexerContaoAdapterBundle\EventListener\GetPageLayoutListener:
    tags:
      - { name: contao.hook, hook: getPageLayout, method: getPageLayout, priority: 100 }
  Alnv\ProSearchIndexerContaoAdapterBundle\Search\ProSearchIndexer:
    tags:
      - { name: 'contao.search_indexer' }